### ISSUE TITLE
Can the hashie dependency be relaxed?

### ISSUE THREAD

**Issue by monfresh** [reset/ridley#306]
Hi, I'm trying to install a gem which requires hashie >= 3.2, but I can't because ridley is locking it at < 3.0.0. Does ridley have an incompatibility with hashie > 3.0, or can the dependency be updated?

Thanks!

**Comment by jgrevich** [comment]
:+1: I'm need of this too.

**Comment by reset** [comment]
Thanks for the report. This is fixed in master!
