### ISSUE TITLE
Chef 12 with Ridley?

### ISSUE THREAD

**Issue by loualrid** [reset/ridley#311]
Has anyone tried to use Chef 12 with Ridley yet? I set a Chef 12 server up with no data but I was getting 404 Object Not Found errors whenever I tried to do anything via Ridley (though to be fair knife was returning the same errors even though I could create things via the web UI so I think it was an installation issue).

Still, has anyone had any luck with this? Wondering if it's worth contemplating an upgrade to chef 12 from 11.

**Comment by reset** [comment]
@loualrid aside from [this issue](https://github.com/reset/ridley/pull/309) which was merged, there hasn't been any chatter about incompatibilities with Chef 12. I imagine that you had an installation issue if both knife and Ridley were hitting a 404 object not found error.

I'm going to close this for now but feel free to re-open it if you run into a problem with Ridley and Chef 12.

**Comment by loualrid** [comment]
@reset You were right in a way, it was a configuration issue in my knife.rb. I didn't realize you had to use the format of "https://server_domain_or_IP/organizations/organization_name" for the chef_server_url key with Chef 12.
